*---------------------------
* Bias current
*---------------------------
.param Ibias=4u 

*---------------------------
* Transistor dimensions
*---------------------------
.param W1=31.25u
.param L1=1.05u
.param W2=31.25u
.param L2=1.05u

.param W3=7.24u
.param L3=1.05u
.param W4=7.24u
.param L4=1.05u

.param W5=62.5u
.param L5=1.05u
.param W6=625u
.param L6=1.05u

.param W7=145u
.param L7=1.05u
.param W8=62.5u
.param L8=1.05u

*---------------------------
* Compensation network
*---------------------------
.param Rc=1.2k
.param Cc=4.8p

*---------------------------
* Feedback network
*---------------------------
.param Cf=150f
.param Cin=15p
.param Rf=1T